export const SIGNED_IN = 'SIGNED_IN';
export const PARKING_LOCATION = "PARKING_LOCATION";
export const BOOKING_SLOTS = "BOOKING_SLOTS";
export const BOOKINGS_LIST = "BOOKINGS_LIST";
export const USERS_LIST = "USERS_LIST";
export const MY_BOOKING_LIST = "MY_BOOKING_LIST";
export const FEEDBACK_LIST = "FEEDBACK_LIST";